import 'package:flutter/material.dart';

class AppTheme {
  static const _regular = FontWeight.w400;
  static const _medium = FontWeight.w500;
  static const _semiBold = FontWeight.w600;
  TextTheme get _textTheme => TextTheme(
    headlineMedium: const TextStyle(fontWeight: _medium, fontSize: 25),
    bodySmall: TextStyle(
      fontWeight: _regular,
      // color: _defaultColorScheme.onSurfaceVariant,
    ),
    headlineSmall: const TextStyle(fontWeight: _medium),
    titleMedium: const TextStyle(fontWeight: _medium),
    bodyLarge: const TextStyle(fontWeight: _regular),
    titleSmall: const TextStyle(fontWeight: _medium),
    bodyMedium: const TextStyle(fontWeight: _regular),
    titleLarge: const TextStyle(fontWeight: _semiBold),
    labelLarge: const TextStyle(fontWeight: _semiBold),
  );
  ColorScheme get _colorScheme => ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF1D2228),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFB0B2C0),
    onPrimaryContainer: Color(0xFF000000),
    primaryFixed: Color(0xFFCDD0D3),
    primaryFixedDim: Color(0xFFA5AAAE),
    onPrimaryFixed: Color(0xFF000000),
    onPrimaryFixedVariant: Color(0xFF000000),
    secondary: Color(0xFFFB8122),
    onSecondary: Color(0xFF000000),
    secondaryContainer: Color(0xFFFFB680),
    onSecondaryContainer: Color(0xFF000000),
    secondaryFixed: Color(0xFFF2C49F),
    secondaryFixedDim: Color(0xFFECA66F),
    onSecondaryFixed: Color(0xFF000000),
    onSecondaryFixedVariant: Color(0xFF1A0C01),
    tertiary: Color(0xFFEA9654),
    onTertiary: Color(0xFF000000),
    tertiaryContainer: Color(0xFFE9CBAB),
    onTertiaryContainer: Color(0xFF000000),
    tertiaryFixed: Color(0xFFEBCEB6),
    tertiaryFixedDim: Color(0xFFE1B38F),
    onTertiaryFixed: Color(0xFF090401),
    onTertiaryFixedVariant: Color(0xFF321A06),
    error: Color(0xFFB00020),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFCD9DF),
    onErrorContainer: Color(0xFF000000),
    surface: Color(0xFFFFFFFF),
    onSurface: Color(0xFF000000),
    surfaceDim: Color(0xFFE0E0E0),
    surfaceBright: Color(0xFFFDFDFD),
    surfaceContainerLowest: Color(0xFFFFFFFF),
    surfaceContainerLow: Color(0xFFF8F8F8),
    surfaceContainer: Color(0xFFF3F3F3),
    surfaceContainerHigh: Color(0xFFEDEDED),
    surfaceContainerHighest: Color(0xFFE7E7E7),
    onSurfaceVariant: Color(0xFF000000),
    outline: Color(0xFF919191),
    outlineVariant: Color(0xFFD1D1D1),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFF121212),
    onInverseSurface: Color(0xFFFFFFFF),
    inversePrimary: Color(0xFF9EA2A6),
    surfaceTint: Color(0xFF1D2228),
  );

  ThemeData get theme => ThemeData.from(colorScheme: _colorScheme).copyWith(
    appBarTheme: AppBarTheme(
      backgroundColor: _colorScheme.primary,
      foregroundColor: _colorScheme.onPrimary,
    ),
  );
}

/// Dark [ColorScheme] made with FlexColorScheme v8.2.0.
/// Requires Flutter 3.22.0 or later.
class DarkAppTheme extends AppTheme {
  @override
  ColorScheme get _colorScheme => ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFF777A7E),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFF313C42),
    onPrimaryContainer: Color(0xFFFFFFFF),
    primaryFixed: Color(0xFFCDD0D3),
    primaryFixedDim: Color(0xFFA5AAAE),
    onPrimaryFixed: Color(0xFF000000),
    onPrimaryFixedVariant: Color(0xFF000000),
    secondary: Color(0xFFFCB075),
    onSecondary: Color(0xFF000000),
    secondaryContainer: Color(0xFFD97B18),
    onSecondaryContainer: Color(0xFFFFFFFF),
    secondaryFixed: Color(0xFFF2C49F),
    secondaryFixedDim: Color(0xFFECA66F),
    onSecondaryFixed: Color(0xFF000000),
    onSecondaryFixedVariant: Color(0xFF1A0C01),
    tertiary: Color(0xFFEFB383),
    onTertiary: Color(0xFF000000),
    tertiaryContainer: Color(0xFFA75F27),
    onTertiaryContainer: Color(0xFFFFFFFF),
    tertiaryFixed: Color(0xFFEBCEB6),
    tertiaryFixedDim: Color(0xFFE1B38F),
    onTertiaryFixed: Color(0xFF090401),
    onTertiaryFixedVariant: Color(0xFF321A06),
    error: Color(0xFFCF6679),
    onError: Color(0xFF000000),
    errorContainer: Color(0xFFB1384E),
    onErrorContainer: Color(0xFFFFFFFF),
    surface: Color(0xFF121212),
    onSurface: Color(0xFFFFFFFF),
    surfaceDim: Color(0xFF060606),
    surfaceBright: Color(0xFF2C2C2C),
    surfaceContainerLowest: Color(0xFF010101),
    surfaceContainerLow: Color(0xFF0E0E0E),
    surfaceContainer: Color(0xFF151515),
    surfaceContainerHigh: Color(0xFF1D1D1D),
    surfaceContainerHighest: Color(0xFF282828),
    onSurfaceVariant: Color(0xFFFFFFFF),
    outline: Color(0xFF777777),
    outlineVariant: Color(0xFF414141),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFFFFFFFF),
    onInverseSurface: Color(0xFF121212),
    inversePrimary: Color(0xFF404142),
    surfaceTint: Color(0xFF777A7E),
  );
}
